commandsideservice:
  build: ./todo-service/
  restart: unless-stopped
  ports:
    - "8081:8080"

querysideservice:
  build: ./todo-view-service/
  restart: unless-stopped
  ports:
    - "8082:8080"
